### ISSUE TITLE
Ambiguous HTTP method for action

### ISSUE THREAD

**Issue by BenCG3** [urltapas/task-tracker#2]
You need to add [NonAction] for indiquate that is not an action methode.
in src/TaskTracker.Api/Controllers/ErrorController.cs
```C#
[Route("/error")]
[NonAction]
```
Otherwise i have this error :
```C#
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException:` Ambiguous HTTP method for action - TaskTracker.Api.Controllers.ErrorsController.Error
```

**Comment by urltapas** [comment]
thx u for the guidance, i just added [No Action] to resolve the ambiguous method issue
